"""Add tenant_name field to tenants table

Revision ID: e340c902e215
Revises: e9258cf92b4d
Create Date: 2026-01-11 10:21:31.116444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e340c902e215'
down_revision: Union[str, Sequence[str], None] = 'e9258cf92b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add tenant_name column to tenants table
    op.add_column('tenants', sa.Column('tenant_name', sa.String(length=255), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tenants', 'tenant_name')
    # ### end Alembic commands ###
