"""Add tenant-based authentication

Revision ID: e9258cf92b4d
Revises: 3972af504055
Create Date: 2026-01-07 16:44:58.144826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9258cf92b4d'
down_revision: Union[str, Sequence[str], None] = '3972af504055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    connection = op.get_bind()

    # Step 1: Create tenants table only if it doesn't exist
    inspector = sa.inspect(connection)
    if 'tenants' not in inspector.get_table_names():
        op.create_table('tenants',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('password_hash', sa.String(length=255), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
        op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)

        # Step 2: Create default tenant for existing users
        op.execute("""
            INSERT INTO tenants (id, email, password_hash, is_active, created_at, updated_at)
            VALUES (1, 'default@system.local', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqLYpBdzDS', 1, datetime('now'), datetime('now'))
        """)

    # Step 3-8: Use batch mode for SQLite to add columns and constraints
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add new columns (nullable first)
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), server_default='MEMBER', nullable=False))

    # Step 4: Migrate existing users to default tenant
    # Set username = email prefix (part before @) for existing users
    op.execute("""
        UPDATE users
        SET tenant_id = 1,
            username = substr(email, 1, CASE WHEN instr(email, '@') > 0 THEN instr(email, '@') - 1 ELSE length(email) END)
        WHERE tenant_id IS NULL
    """)

    # Step 5-8: Complete the table alteration with constraints
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Create indexes
        batch_op.create_index('ix_users_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('ix_users_username', ['username'], unique=False)

        # Create unique constraint for (tenant_id, username)
        batch_op.create_unique_constraint('uq_tenant_username', ['tenant_id', 'username'])

        # Create foreign key
        batch_op.create_foreign_key('fk_users_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint('uq_tenant_username', 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'username')
    op.drop_column('users', 'tenant_id')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
